apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
spec:
    selector:
        matchLabels:
            app: frontend
    replicas: 1
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: finneganhu/frontend:prom
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8084
                  # env:
                  #     - name: JAEGER_AGENT_HOST
                  #       value: "jaeger"
                  #     - name: JAEGER_AGENT_PORT
                  #       value: "6831"
