# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - rules/rules*.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: customer_service
    static_configs:
      - targets: ['customer:8081']
  - job_name: frontend_service
    static_configs:
      - targets: ['frontend:8084']
  - job_name: jaeger
    static_configs:
      - targets: ['jaeger:14269']
  - job_name: docker
    static_configs:
      - targets: ['192.168.1.185:9323']
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
