apiVersion: v1
kind: Service
metadata:
    name: customer
    labels:
        app: customer
spec:
    ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
        app: customer
