route:
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 3h
  receiver: slack-error

receivers:
- name: slack-error
  slack_configs:
    - channel: '#managed-services-notifications'
      send_resolved: true
      api_url: 'https://hooks.slack.com/services/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'
      icon_url: https://avatars3.githubusercontent.com/u/3380462
      text: "\nDesciption: {{ .CommonAnnotations.description }}"
